### ISSUE TITLE
Do we need the vendor folder within the deployment?

### ISSUE THREAD

**Issue by draschke** [SAP-samples/hana-python-securestore#5]
Realized that my builded .mtar was much bigger as yours and saw that your .mtar file is without the vendor folder.
Do we have to exclude this folder as we build the mtar file?
Is it needed if I want to deploy it to XSA python runtime?

**Comment by andrewlunde** [comment]
The deployer will attempt to satisfy your python module's dependencies if it doesn't find them in the vendor folder.

You might want to remove it from the mtar and watch the logs of the module as it's deploying in order to see if it fails to find the dependencies.  Then you can add them back to the vendor folder as needed.

**Comment by draschke** [comment]
Thanks for your advice!
Tried it, but struggle with an other deployment issue, so that I'm not able to prove if this would work.
Saw only that the mtar file is much more smaller (without node_modules and vendor) after including the ignore parameter.

```
mta.yaml
   build-parameters:
    ignore: ["node_modules/"] 

   build-parameters:
    ignore: ["vendor/"]
```
The deployment fails with this issue **raise ValueError('SSL support not available')** and I don't get it solved.
(pip3 installation of pyOpenSSL runs in an error)
Think the reason is, because I'm on an older SLES version ("12-SP2") within a docker container and can't upgrade the SLES version so far as I know.
